# Folder where results are stored on this machine.
result-path: "./artifact-results-test"

# Default settings used for all targets defined below. Can be overwritten
# by a per target basis.
default-target-settings:
    # Fuzzers for which the target should be run.
    fuzzers:    
        - ft
    # Duration of each individual run.
    # This was 24h during the papers evaluation.
    # A runtime of 12h should be sufficient to observe the same trends as in the paper.
    run-duration: 1h
    # Number of times to repeat each experiment for each target.
    # This was set to 10 for the paper's evaluation.
    # Depending on the available resources, this should be increased to get statistically more meaningful results.
    repetitions: 1
    # Number of cores to allocate per run. This will be capped by the cores
    # available on the respective machines.
    # This was 13 for the paper's evaluation.
    # We observed that this number of cores should be sufficient to replicate the results of the paper on most targets.
    cores-per-run: 4
    # The target will only deployed on server with a matching tag.
    allowed-tags: ["eval"]

targets:
 - "artifact_openssl_client_server_1":
        # The yaml config of the target
        config: "~/fuzztruction/fuzztruction-experiments/comparison-with-state-of-the-art/configurations/networked/openssl/openssl_client_server_1.yml"
        # Targets of which the dependencies must be installed.
        # I.e., folder names in binaries/networked
        build-target-dependencies:
            - openssl
        # See default-target-setting for more details
        target-settings:
          fuzzers:
              - ft

remotes:
    # Remote name.
    - "localhost":
        # The remote address. The address given here must be a valid argument to `ssh` and the access must be possible without password authentication.
        # Furthermore, the user must be able to execute `sudo`without being required to enter a password.`
        # So, for example, `ssh local -o IdentityAgent=none <ssh-address> sudo id -u` should print `0`` without any further interaction.
        # This setup is also necessary if the remote and the host running the `eval.py` are the same.
        # To facilitate this, you need to deploy a public key to the remote server and add a new entry to the .ssh/config:
        # Host <ssh-address>
        #   Hostname <some-ip>
        #   IdentityFile ~/.ssh/<key-deployed-on-remote>
        #   IdentityAgent none
        #
        # Make sure the the connection to the remote is working by running the following command which enforces to not use the ssh agent which is not
        # available when running the `eval.py` script in a tmux session.
        #   ssh -o IdentityAgent=none <ssh-address> sudo id -u
        # Also, make sure that the key is trusted, i.e., added to your known_hosts file.
        ssh-address: "localhost"
        # The number of cores available on the remote server. We advise to set this to the number of physical cores, excluding hyper-threads.
        cores: 4
        tags: ["eval"]
